re add 2FA, add userdb cli, fix idle systems, add statistics..
A-c0rN/ASMARA pull request #33
Opened 2024-02-06 03:18 UTC by reggietorres

This is by far, the biggest update feature wise,

2FA has been readded, it now utilizes authenticator phone apps, if it has a qr code feature, it probably will work.. 
Statistics have been added, although they aren't good yet..
Idle has been fixed (again)

and the userdb CLI has been added

using this python CLI tool you can do the following

list users
list user's passwords (only if you pass --show-pass)

add user
delete user from id or username

and the README has been moderized to use userdb,

I've updated requirements.txt to include the modules needed to run the webserver

2024-02-27 18:05 UTC, reggietorres commented
userdb cli will be able to list even more information with --advanced, but only for a specific user, and only when we implement the settings page

2024-02-29 16:33 UTC, A-c0rN commented on templates/index.html
> +                logoutActionTimeout = setTimeout(logoutUser,  30000); //  30 seconds to click the button
It isn't needed, but a countdown timer till logout with the button would be awesome!

2024-02-29 16:50 UTC, A-c0rN requested changes
Left a few comments, feel free to read through and reach out if you have questions!

2024-02-29 16:50 UTC, A-c0rN commented on templates/verify_code.html
> +            <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" action="/verify_code?username={{ request.args.get('username') }}" method="post">
Need to look into a better way of doing this, such as with cookies. Putting any user information in the request calls is a no-go.

2024-02-29 16:50 UTC, A-c0rN commented on userdb.py
> +colorama.init()
Let's try and steer clear of colorization, it doesn't work the same on all platforms, and is not really needed.

2024-02-29 16:50 UTC, A-c0rN commented on userdb.py
> +            username VARCHAR(50),
I have a few people I know who have longer User / passes, so let's expand this to 128.
Also allows some pass gens that by default use 64 char passes.

2024-02-29 16:50 UTC, A-c0rN commented on userdb.py
> +        print("Notice: Due to Security Reasons, Password is not shown unless passing --show-pass")
This shouldn't be an option by default.

2024-02-29 16:50 UTC, A-c0rN commented on userdb.py
> +def make2fa(username):
If we can make this also return a code, Some 2FA apps support both a QR code and a backup code input.
We want both, so the user has an easier time registering, and has backup codes if locked out.

2024-02-29 16:50 UTC, A-c0rN commented on userdb.py
> +    cursor.execute(query, (username, password, secret))
Passwords should NEVER be stored as plaintext, including in the database. 
This needs to be handled with a one-way hash, and have the client also hash the pass.

One good way to do this:
Server Side:
Get Pass (First Time) > One Way Hash > One Way Hash with known salt (Can be a number based on the machine) > Database

Client Side:
Get Pass > One Way Hash (Well before network) > Server

For checking:
Client > Hash > Server
Server > Known Salt Hash > DB Query

This avoids transferring the password in any way that is decodable, especially over the network.
This also means the server doesn't know what your password actually is, and makes the database (If Leaked) harder to crack (As you would need both the original password hash, which is lost when the server does the Known Salt Hash, and you would also need the Known Salt, which should be lost on moving the DB off the source server.)

2024-02-29 16:50 UTC, A-c0rN commented on web.py
> +import pyotp
We can offload this to the builtin random and hashing class, reduces need for outside libs.

2024-02-29 16:56 UTC, reggietorres commented
Workin on it! the next commit won't have anything to do with the stuff above though, i gotta push my current commits to my fork first

2024-02-29 16:59 UTC, reggietorres commented on userdb.py
> +def make2fa(username):
all the QRCODES required to register are stored in a folder, but il look into it anyways, i get where you are coming from

2024-02-29 17:23 UTC, reggietorres commented on userdb.py
> +colorama.init()
Done

2024-02-29 17:26 UTC, reggietorres commented on userdb.py
> +            username VARCHAR(50),
Done

2024-02-29 18:18 UTC, reggietorres commented on userdb.py
> +    cursor.execute(query, (username, password, secret))
was a pain in the ass cause i first tried with bcrypt, and that failed, so we have to use sha, and it works now

2024-02-29 18:23 UTC, reggietorres commented on userdb.py
> +def make2fa(username):
i don't really see an *easy* way of implementing backup codes atm, and the qrcodes can be taken out of the qrcodes folder and saved as a backup, so maybe in the future we can implement that, but at the moment, i think we are good

2024-02-29 18:25 UTC, reggietorres commented on web.py
> +import pyotp
can we do it, probably, but its just easier this way, but il meet you in the middle here, instead of importing that whole module, il just import the thing we use.

2024-02-29 18:26 UTC, reggietorres commented on userdb.py
> +def make2fa(username):
in pyotp you can print out the current otp code, so if you really want it, i can add it

2024-03-01 18:56 UTC, reggietorres commented on templates/index.html
> +                logoutActionTimeout = setTimeout(logoutUser,  30000); //  30 seconds to click the button
done

2024-03-02 00:24 UTC, A-c0rN requested changes
I'll pull this down later, and work on it when I am not swamped with work and social events.
Thank you!

2024-03-02 00:24 UTC, A-c0rN commented on templates/encode.html
> +                        <option value="PEP">PEP - National Public Warning System</option>
Oh yea! It's not a great idea to allow the user to send PEP codes.
These should be limited to FEMA and the gov themselves.

2024-03-02 00:24 UTC, A-c0rN commented on templates/encode.html
> +                        showAlertPopup('Congratulations, You sent a real alert, If this was a mistake, get ready to get fired from whatever workplace you are at right now! cause this is a LIVE ALERT!
I would tone this back a bit, however funny this might be. :3

2024-03-02 00:24 UTC, A-c0rN commented on tests/socketservertest.py
> +    correct_password = "secret_password"  # Hardcoded*1 password
We should have instead of a HC password, a randomized default pass on install.
This can be displayed first time around.

Example: Pi-Hole. It generates a random admin password that is displayed after initial setup, so no bad actor can do malicious acts before setup :3

2024-03-02 00:24 UTC, A-c0rN commented on tests/socketservertest.py
> +                        jjjhhmm = split_strings[5]
I have a one-liner for this in python, I can update this in a bit!

2024-03-02 00:24 UTC, A-c0rN commented on userdb.py
> +        issuer_name = x509.Name([
If both the issuer and the name are the same, we don't need both.

2024-03-02 00:24 UTC, A-c0rN commented on userdb.py
> +        connection = mysql.connector.connect(
We should *probably* put a better DB username / password in here...

2024-03-02 00:24 UTC, A-c0rN commented on userdb.py
> +def make2fa(username):
I can look into this. If there's an easier way to do this, we can also tie it to the hashed user password so the same code works across units as long as the user has the same pass :3

2024-03-02 00:24 UTC, A-c0rN commented on web.py
> +    def getJJJHHMM():
This can be simplified to `return datetime.utcnow().strftime("%j%H%M")`

2024-03-02 00:24 UTC, A-c0rN commented on web.py
> +        app.run(debug=True)
We should be VERY cautious about running in debug mode!
If possible, this should pull from environment variables.

2024-03-02 00:48 UTC, reggietorres commented on userdb.py
> +def make2fa(username):
> I can look into this. If there's an easier way to do this, we can also tie it to the hashed user password so the same code works across units as long as the user has the same pass :3

I already see how we could do that, il also look into it

2024-03-02 00:49 UTC, reggietorres commented on templates/encode.html
> +                        <option value="PEP">PEP - National Public Warning System</option>
It's just there for show right now, i was thinking we could make a test mode for the endec where no alerts actually get sent out, and its like for self testing?

2024-03-02 00:50 UTC, reggietorres commented on templates/encode.html
> +                        showAlertPopup('Congratulations, You sent a real alert, If this was a mistake, get ready to get fired from whatever workplace you are at right now! cause this is a LIVE ALERT!
I could add a "fuck me sideways" option in settings lol

2024-03-02 00:50 UTC, reggietorres commented on tests/socketservertest.py
> +    correct_password = "secret_password"  # Hardcoded*1 password
Yeah, well its a test socket server, its here to tell you how it works, so you can implement it into ASMARA for encoding, cause thats where all encoding requests go

2024-03-02 00:51 UTC, reggietorres commented on tests/socketservertest.py
> +                        jjjhhmm = split_strings[5]
Sounds great!

2024-03-02 00:51 UTC, reggietorres commented on userdb.py
> +        issuer_name = x509.Name([
I did it that way because it makes it look slightly cooler in firefox, but you can change it, i don't mind

2024-03-02 00:51 UTC, reggietorres commented on userdb.py
> +        connection = mysql.connector.connect(
Test Build

2024-03-02 00:52 UTC, reggietorres commented on web.py
> +    def getJJJHHMM():
Yeah you're right, my bad

2024-03-02 00:52 UTC, reggietorres commented on web.py
> +        app.run(debug=True)
Test Build

2024-03-02 01:03 UTC, reggietorres commented on templates/encode.html
> +                        <option value="PEP">PEP - National Public Warning System</option>
commented them out for now

2024-03-02 01:55 UTC, reggietorres commented on userdb.py
> +def make2fa(username):
> I can look into this. If there's an easier way to do this, we can also tie it to the hashed user password so the same code works across units as long as the user has the same pass :3

we could do it where the user can choose between single endec mode and multi endec mode, so they can either pick between same codes or randomized codes for each instance (which would be more secure)

2024-03-02 20:59 UTC, reggietorres reviewed
whoops, unverified, git is weird today

2024-03-10 03:54 UTC, A-c0rN approved these changes
Approving this to get it into the repo, I'll pull down and work on it ASAP. Life been complicated for me for the last bit ;-;

2024-03-10 03:54 UTC, merged